CantiereApp/Models/Cantiere.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CantiereApp.Models
{
    public class Cantiere
    {
        public string NomeCliente { get; set; }
        public string EmailCliente { get; set; }
        public string Luogo { get; set; }
    }

    public class NuovoIntervento
    {
        public string NomeCliente { get; set; }
        public string Luogo { get; set; }
        public string Tipologia { get; set; }
        public string Lavoro { get; set; }
        public string Note { get; set; }
        public decimal Prezzo { get; set; }
        public string Foto { get; set; }
    }
}

CantiereApp/Controllers/CantiereController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using CantiereApp.Models;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CantiereApp.Controllers
{
    public class CantiereController : Controller
    {
        // GET: Cantiere
        public async Task<ActionResult> Index()
        {
            var list = await GetCantieri();

            return View(list);
        }

        [HttpGet]
        public IActionResult NuovoCantiere()
        {
            return View();
        }

        public async Task<IEnumerable<Cantiere>> GetCantieri()
        {
            using (SqlConnection connection = new SqlConnection(""))
            {
                var query = $"select * from [dbo].[Cantiere]";

                return (await connection.QueryAsync<Cantiere>(query)).ToList();
            }
        }


        [HttpPost]
        public async Task<IActionResult> NuovoCantiere([FromForm] Cantiere c)
        {
            Cantiere ca = new Cantiere
            {
                NomeCliente = c.NomeCliente,
                Luogo = c.Luogo,
                EmailCliente=c.EmailCliente
            };

            using (SqlConnection connection = new SqlConnection(""))
            {
                var query = "INSERT INTO [dbo].[Cantiere]" +
                            "([NomeCliente], [Luogo] ,[EmailCliente])  " +
                            "VALUES (@NomeCliente, @Luogo, @EmailCliente)";

                connection.Execute(query, ca);

                connection.Close();
            }

            return View("Index");

        }

        // GET: Cantiere/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cantiere/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cantiere/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cantiere/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cantiere/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cantiere/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cantiere/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CantiereApp/Controllers/InterventoController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using CantiereApp.Models;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CantiereApp.Controllers
{
    public class InterventoController : Controller
    {
        // GET: Intervento
        public ActionResult Index()
        {
            return View("NuovoIntervento");
        }

        public ActionResult NuovoIntervento(string NomeCliente, string luogo)
        {
            //NuovoIntervento n = new NuovoIntervento()
            //{
            //    NomeCliente = NomeCliente,
            //    Luogo = luogo

            //};
            return View();
        }

        public async Task<IActionResult> InserisciIntervento ([FromForm] Intervento i)
        {
            Intervento intervento = new Intervento()
            {
                NomeCliente = i.NomeCliente,
                Data = DateTime.Now,
                Luogo = i.Luogo,
                Lavoro = i.Lavoro,
                Tipologia = i.Tipologia,
                Note = i.Note,
                Prezzo = i.Prezzo,
                Foto = ""
            };

            if (i.Tipologia == "elettrico")
            {
                using (SqlConnection connection = new SqlConnection(""))
                {
                    var query = "INSERT INTO [dbo].[InterventoEsterno]" +
                                "([NomeCliente], [Luogo] , [Data], [Lavoro], [Foto]) " +
                                "VALUES (@NomeCliente, @Luogo, @Data, @Lavoro, @Foto)";

                    connection.Execute(query, intervento);

                    connection.Close();
                }

            }
            
           
           
            if (i.Tipologia != "elettrico")
            {
                using (SqlConnection connection = new SqlConnection(""))
                {
                    var query = "INSERT INTO [dbo].[Intervento]" +
                                "([NomeCliente], [Luogo] , [Data], [Lavoro], [Tipologia], [Note], [Prezzo], [Foto]) " +
                                "VALUES (@NomeCliente, @Luogo, @Data, @Lavoro, @Tipologia, @Note, @Prezzo, @Foto)";

                    connection.Execute(query, intervento);

                    connection.Close();
                }
            }

            return RedirectToAction("Index", "Cantiere");
        }


        // GET: Intervento/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Intervento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Intervento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Intervento/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Intervento/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Intervento/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Intervento/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CantiereApp/Views/Cantiere/Index.cshtml
@model IEnumerable<CantiereApp.Models.Cantiere>

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<h4>Cantiere</h4>
<hr />
<p>
    <a asp-controller="Cantiere" asp-action="NuovoCantiere" class="btn btn-primary">Crea nuovo cantiere</a>
</p>
<br />

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NomeCliente)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EmailCliente)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Luogo)
                </th>
</thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Luogo)
                </td>
                <td>
                    @Html.ActionLink("Aggiungi Intervento", "Index", "Intervento", new { NomeCliente = item.NomeCliente, Luogo = item.Luogo }, new { @class = "btn btn-primary btn-large" })
                </td>
            </tr>
            }
        </tbody>
    </table>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

CantiereApp/Views/Cantiere/NuovoCantiere.cshtml
@model CantiereApp.Models.Cantiere

@{
    ViewData["Title"] = "NewActivity";
}

<h2>NuovoCantiere</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="NuovoCantiere">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeCliente" class="control-label"></label>
                <input asp-for="NomeCliente" class="form-control" />
                <span asp-validation-for="NomeCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailCliente" class="control-label"></label>
                <input asp-for="EmailCliente" class="form-control" />
                <span asp-validation-for="EmailCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luogo" class="control-label"></label>
                <input asp-for="Luogo" class="form-control" />
                <span asp-validation-for="Luogo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>